# Generated by Django 4.2 on 2025-02-18 12:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200, unique=True, verbose_name="эл.почта"
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="страна"
                    ),
                ),
                ("city", models.CharField(max_length=200, verbose_name="город")),
                ("street", models.CharField(max_length=200, verbose_name="улица")),
                ("house_number", models.IntegerField(verbose_name="номер дома")),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
                "db_table": "contacts",
                "db_table_comment": "Контакты сети",
                "ordering": ["email"],
            },
        ),
        migrations.AddIndex(
            model_name="contact",
            index=models.Index(
                fields=["city", "email", "country"], name="contacts_city_e3c425_idx"
            ),
        ),
    ]
