# Generated by Django 4.2 on 2025-02-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0002_remove_product_release_date_greater_or_equal_now_and_more"),
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                (
                    "debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="задолженность перед поставщиком",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "contacts",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="contacts.contact",
                        verbose_name="контакты",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        related_name="producer",
                        to="products.product",
                        verbose_name="продукты",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="retail_network.networknode",
                        verbose_name="поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "звено сети",
                "verbose_name_plural": "звенья сети",
                "db_table": "network_nodes",
                "db_table_comment": "Звено сети",
                "ordering": ["title"],
            },
        ),
        migrations.AddIndex(
            model_name="networknode",
            index=models.Index(fields=["title"], name="network_nod_title_85f042_idx"),
        ),
    ]
