# Generated by Django 4.2 on 2025-02-18 12:18

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="release_date_greater_or_equal_now",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "release_date__gt",
                        datetime.datetime(2025, 2, 18, 12, 18, 20, 989889),
                    )
                ),
                name="release_date_greater_or_equal_now",
            ),
        ),
    ]
