# Generated by Django 4.2 on 2025-02-16 06:04

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "release_date__gt",
                        datetime.datetime(2025, 2, 16, 6, 4, 21, 566670),
                    )
                ),
                name="release_date_greater_or_equal_now",
            ),
        ),
    ]
